import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen h-screen flex flex-col items-center">
        <h1 className="text-center text-6xl w-96 m-12">Welcome to List app</h1>
        <p>Get started by creating a list</p>
      </main>

      <footer>asdf</footer>
    </div>
  );
};

export default Home;
